import { useState, useRef, useEffect } from 'react'
import { api } from '../api'
import jsPDF from "jspdf";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";


const SUGGESTIONS = [
  'Sunny Kumar ko aaj present mark karo',
  'Kajal Kumari ka attendance summary dikhao',
  'Is month sabse kam attendance kiski hai?',
  'Aaj kisne attendance nahi mark ki?',
]

export default function ChatAgent() {
  const [messages, setMessages] = useState([])
  const [showWelcome, setShowWelcome] = useState(true)

  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [listening, setListening] = useState(false)

  const bottomRef = useRef(null)
  const recognitionRef = useRef(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({
      behavior: 'auto',
      block: 'end',
    })
  }, [messages])

  const speechSupported =
    typeof window !== 'undefined' &&
    (window.SpeechRecognition || window.webkitSpeechRecognition)

  function toggleVoice() {
    if (!speechSupported) return

    if (listening) {
      recognitionRef.current?.stop()
      return
    }

    const SpeechRecognition =
      window.SpeechRecognition || window.webkitSpeechRecognition

    const recognition = new SpeechRecognition()

    recognition.lang = 'hi-IN'
    recognition.interimResults = false
    recognition.maxAlternatives = 1

    recognition.onstart = () => setListening(true)
    recognition.onend = () => setListening(false)
    recognition.onerror = () => setListening(false)

    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript
      setInput(transcript)
      send(transcript)
    }

    recognitionRef.current = recognition
    recognition.start()
  }

  function downloadPDF(text) {
    const doc = new jsPDF("p", "mm", "a4")

    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()

    let y = 20

    // ----------------------------
    // Clean AI Response
    // ----------------------------

    let cleanText = text
      .replace(/\*\*/g, "")
      .replace(/__/g, "")
      .replace(/`/g, "")
      .replace(/#{1,6}/g, "")
      .replace(/✅/g, "[OK]")
      .replace(/❌/g, "[X]")
      .replace(/⚠️/g, "[!]")
      .replace(/⚠/g, "[!]")
      .replace(/📊/g, "")
      .replace(/📈/g, "")
      .replace(/📢/g, "")
      .replace(/🧠/g, "")
      .replace(/🔎/g, "")
      .replace(/📄/g, "")
      .replace(/✔/g, "-")
      .replace(/•/g, "-")
      .trim()

    // ----------------------------
    // Header
    // ----------------------------

    doc.setFillColor(27, 73, 101)
    doc.rect(0, 0, pageWidth, 25, "F")

    doc.setTextColor(255, 255, 255)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(18)
    doc.text("Swasthya Sathi AI", 15, 12)

    doc.setFontSize(10)
    doc.text("Bihar Health Department", 15, 19)

    y = 35

    doc.setTextColor(0, 0, 0)

    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.text("Attendance & Operations Report", 15, y)

    y += 10

    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")

    doc.text(
      `Generated : ${new Date().toLocaleString()}`,
      15,
      y
    )

    y += 8

    doc.line(15, y, pageWidth - 15, y)

    y += 10

    // ----------------------------
    // Report Title
    // ----------------------------

    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.text("AI Response", 15, y)

    y += 8

    doc.setFont("helvetica", "normal")
    doc.setFontSize(11)

    // ----------------------------
    // Print Line by Line
    // ----------------------------

    const paragraphs = cleanText.split("\n")

    paragraphs.forEach((para) => {

      if (!para.trim()) {
        y += 6
        return
      }

      const lines = doc.splitTextToSize(para, 175)

      lines.forEach((line) => {

        if (y > pageHeight - 25) {

          doc.setFontSize(9)
          doc.setTextColor(120)

          doc.text(
            "Generated by Swasthya Sathi AI",
            15,
            pageHeight - 10
          )

          doc.addPage()

          y = 20

          doc.setFontSize(11)
          doc.setTextColor(0)
        }

        // Highlight headings

        if (
          line.includes("Worker") ||
          line.includes("Status") ||
          line.includes("Recommendation") ||
          line.includes("Result") ||
          line.includes("Attendance") ||
          line.includes("Summary") ||
          line.includes("Report")
        ) {
          doc.setFont("helvetica", "bold")
        } else {
          doc.setFont("helvetica", "normal")
        }

        doc.text(line, 18, y)

        y += 6
      })

      y += 2
    })

    // ----------------------------
    // Footer
    // ----------------------------

    doc.setFontSize(9)
    doc.setTextColor(120)

    doc.line(15, pageHeight - 18, pageWidth - 15, pageHeight - 18)

    doc.text(
      "Generated by Swasthya Sathi AI",
      15,
      pageHeight - 10
    )

    doc.text(
      `Page ${doc.getCurrentPageInfo().pageNumber}`,
      pageWidth - 35,
      pageHeight - 10
    )

    doc.save(`Swasthya-Sathi-${Date.now()}.pdf`)
  }


  async function send(text) {
    const msg = (text ?? input).trim()

    if (!msg || loading) return

    setMessages((m) => [...m, { role: 'user', text: msg }])
    setShowWelcome(false)

    setInput('')
    setLoading(true)

    try {
      const res = await api.sendChat(msg)

      setMessages((m) => [
        ...m,
        {
          role: 'agent',
          text: res.reply,
          actions: res.actions_taken || [],
        },
      ])
    } catch {
      setMessages((m) => [
        ...m,
        {
          role: 'agent',
          text: '❌ AI Agent is temporarily unavailable. Please try again.',
          actions: [],
        },
      ])
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="glass flex flex-col h-full min-h-[520px] lg:sticky lg:top-6">
      <div className="p-4 border-b border-line flex items-center gap-2">
        <span className="w-2 h-2 rounded-full bg-pulse animate-pulse" />
        <h2 className="font-display font-semibold text-sm">🤖 AI Operations Agent</h2>
        <span className="text-[10px] text-white/35 ml-auto">
          AI Multi-Agent Runtime
        </span>
      </div>

      <div className="flex-1 overflow-y-auto scrollbar-thin p-4 space-y-3">
        {showWelcome && (
          <div className="flex justify-start">
            <div className="max-w-[90%] sm:max-w-[85%] rounded-2xl rounded-bl-sm bg-white/5 border border-line shadow-lg px-3.5 py-2.5 text-sm leading-relaxed whitespace-pre-wrap">
              {`👋 Welcome to Swasthya Sathi AI

AI Operations Agent
Bihar Health Department

I monitor and manage attendance across the Bihar PHC Network.

Capabilities

✅ Mark attendance
📊 Attendance summaries
⚠ Detect low attendance
📈 Weekly analytics
📢 Daily operational reports

Ask me:

• Mark Sunny Kumar present today
• Show Kajal Kumari attendance summary
• Who has the lowest attendance this month?
• Who has not marked attendance today?`}
            </div>
          </div>
        )}
        {messages.map((m, i) => (
          <div
            key={`${m.role}-${i}-${m.text.slice(0, 20)}`}
            className={`flex ${m.role === 'user'
              ? 'justify-end'
              : 'justify-start'
              }`}
          >
            <div
              className={`max-w-[90%] sm:max-w-[85%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed whitespace-pre-wrap ${m.role === 'user'
                ? 'bg-gradient-to-br from-pulse2 to-pulse2/70 text-white rounded-br-sm'
                : 'bg-white/5 border border-line rounded-bl-sm shadow-lg'
                }`}
            >
              {m.role === "agent" ? (
                <div className="prose prose-invert max-w-none">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {m.text}
                  </ReactMarkdown>
                </div>
              ) : (
                <div className="whitespace-pre-wrap">
                  {m.text}
                </div>
              )}

              {m.actions?.length > 0 && (
                <div className="mt-2 pt-2 border-t border-white/10 flex flex-wrap gap-1.5">
                  {m.actions.map((a, j) => (
                    <span
                      key={j}
                      className="text-[10px] px-2 py-0.5 rounded-full bg-pulse/15 text-pulse border border-pulse/25"
                    >
                      ✓ {a}
                    </span>
                  ))}
                </div>
              )}

              {m.role === "agent" && i > 0 && (
                <div className="mt-3 flex gap-2">
                  <button
                    onClick={() => downloadPDF(m.text)}
                    className="text-xs px-3 py-2 rounded-lg bg-green-600 hover:bg-green-700 transition-colors text-white"
                  >
                    📄 Download PDF
                  </button>
                </div>
              )}
            </div>
          </div>
        ))}

        {loading && (
          <div className="flex justify-start">
            <div className="bg-white/5 border border-line rounded-2xl rounded-bl-sm px-4 py-3 text-sm text-white/70">
              🧠 Processing...
            </div>
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      <div className="p-3 flex flex-wrap gap-1.5 border-t border-line">
        {SUGGESTIONS.map((s) => (
          <button
            key={s}
            onClick={() => send(s)}
            className="text-[11px] px-3 py-1 rounded-full border border-line text-white/50 hover:text-pulse hover:border-pulse/40"
          >
            {s}
          </button>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault()
          send()
        }}
        className="p-3 border-t border-line flex items-center gap-2"
      >
        <input
          autoFocus
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={
            listening
              ? 'Sun raha hoon…'
              : 'Type in Hindi, English or Hinglish…'
          }
          className="flex-1 bg-white/5 border border-line rounded-xl px-4 py-2.5 text-sm outline-none focus:border-pulse/50 placeholder:text-white/30 transition-colors"
        />

        {speechSupported && (
          <button
            type="button"
            onClick={toggleVoice}
            className={`w-11 h-11 flex items-center justify-center rounded-xl border ${listening
              ? 'bg-danger/20 border-danger/40 text-danger animate-pulse'
              : 'bg-white/5 border-line text-white/50 hover:text-pulse hover:border-pulse/40'
              }`}
          >
            🎤
          </button>
        )}

        <button
          type="submit"
          disabled={loading}
          className="px-5 py-2.5 rounded-xl bg-gradient-to-br from-pulse to-pulse2 text-[#080B10] font-semibold hover:scale-105 transition-transform disabled:opacity-50 disabled:hover:scale-100"
        >
          Send
        </button>
      </form>
    </div>
  )
}